### ISSUE TITLE
an account should not be mandatory and it should be possible to refer to account in main config

### ISSUE THREAD

**Issue by petri** [koodaamo/docproc#3]
When adding a simple web2txt pipe using packaged tasks, docop fails due to not finding "account".

Adding account name field to the source does not help. Adding the corresponding account in accounts section of main config does not help (!). Only resolution is adding the full account setup to the source such as:

```
sources:
  mycompany:
    account: mysite
    resources:
      - https://ksksjdkjs.ajasajjj.fi

accounts:
  mysite:
    dummy: nada
```
